name: PhongSatThan
version: 1.0
main: me.tanluc.phongsatthan.MobContracts
author: TanLuc remaked from MobContracts
description: Defeat epic mobs, and collect bounties in Mobcontracts
softdepend: [PlaceholderAPI]
#api-version: 1.16
commands:
  phongsatthan:
    aliases: [pst]
    description: Main PhongSatThan command
    usage: /phongsatthan
    permission-message: 'Permission denied.'
    permission: mobcontracts.core